# Generated by Django 5.1.15 on 2026-07-09 20:16

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('fingerprint', models.CharField(db_index=True, max_length=128)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
                ('platform', models.CharField(blank=True, default='web', max_length=64)),
                ('trusted', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auth_device',
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('result', models.CharField(choices=[('SUCCESS', 'Success'), ('FAIL', 'Fail'), ('LOCKED', 'Locked')], max_length=16)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('device_fingerprint', models.CharField(blank=True, default='', max_length=128)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'auth_login_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('refresh_token_hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('family_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'auth_session',
            },
        ),
    ]
