# Generated by Django 5.1.15 on 2026-07-09 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loginhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersession',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='auth_service.device'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', 'last_seen'], name='auth_device_user_id_216aa6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('user', 'fingerprint')},
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['email', 'created_at'], name='auth_login__email_8b63d3_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'expires_at'], name='auth_sessio_user_id_0b2899_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['family_id'], name='auth_sessio_family__1ca4ce_idx'),
        ),
    ]
