# Generated by Django 5.1.15 on 2026-07-09 20:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('legal_name', models.CharField(max_length=255)),
                ('trade_name', models.CharField(blank=True, default='', max_length=255)),
                ('base_currency', models.CharField(default='AED', max_length=8)),
                ('country', models.CharField(default='AE', max_length=2)),
                ('tax_registration_no', models.CharField(blank=True, default='', max_length=64)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tenancy_company',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('edition', models.CharField(default='STARTER', max_length=32)),
                ('modules', models.JSONField(blank=True, default=list)),
                ('limits', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tenancy_plan',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='tenancy.company')),
            ],
            options={
                'db_table': 'tenancy_branch',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('SHARED', 'Shared schema'), ('SCHEMA', 'Schema per tenant'), ('DEDICATED', 'Dedicated database')], default='SHARED', max_length=16)),
                ('status', models.CharField(choices=[('PROVISIONING', 'Provisioning'), ('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('ARCHIVED', 'Archived')], default='PROVISIONING', max_length=16)),
                ('region', models.CharField(default='asia-dubai', max_length=32)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='tenancy.plan')),
            ],
            options={
                'db_table': 'tenancy_tenant',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='tenancy.tenant'),
        ),
        migrations.CreateModel(
            name='TenantUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=16)),
                ('is_owner', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_users', to='tenancy.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tenancy_tenant_user',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='tenancy.branch')),
            ],
            options={
                'db_table': 'tenancy_warehouse',
            },
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['company', 'is_active'], name='tenancy_bra_company_4608bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('company', 'code')},
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['status', 'created_at'], name='tenancy_ten_status_12522b_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['tenant', 'is_default'], name='tenancy_com_tenant__5b08a0_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantuser',
            index=models.Index(fields=['user', 'status'], name='tenancy_ten_user_id_06daed_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tenantuser',
            unique_together={('tenant', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('branch', 'code')},
        ),
    ]
