# Generated by Django 5.1.15 on 2026-07-11 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlogentry',
            new_name='audit_log_e_categor_6701ce_idx',
            old_name='audit_cat_created_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlogentry',
            new_name='audit_log_e_action_8db933_idx',
            old_name='audit_act_created_idx',
        ),
    ]
