# Generated by Django 5.1.15 on 2026-07-09 20:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncEntityRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('entity_type', models.CharField(db_index=True, max_length=64, unique=True)),
                ('sync_class', models.CharField(choices=[('R', 'Reference'), ('D', 'Document'), ('T', 'Transactional'), ('A', 'Append-only'), ('S', 'Settings')], max_length=1)),
                ('merge_strategy', models.CharField(choices=[('server_wins', 'Server wins'), ('lww', 'Last-write-wins'), ('3way', 'Three-way merge'), ('manual', 'Manual review')], default='lww', max_length=16)),
                ('direction', models.CharField(default='bidirectional', max_length=16)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sync_entity_registry',
            },
        ),
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.CharField(max_length=64)),
                ('conflict_code', models.CharField(db_index=True, max_length=16)),
                ('client_payload', models.JSONField(default=dict)),
                ('server_payload', models.JSONField(default=dict)),
                ('resolution', models.CharField(blank=True, default='pending', max_length=32)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_conflicts', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'sync_conflict',
                'indexes': [models.Index(fields=['tenant', 'resolution', 'created_at'], name='sync_confli_tenant__c50206_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncDeviceCursor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('device_id', models.CharField(max_length=128)),
                ('entity_type', models.CharField(max_length=64)),
                ('cursor_wall_ms', models.BigIntegerField(default=0)),
                ('cursor_logical', models.BigIntegerField(default=0)),
                ('cursor_entity_id', models.CharField(blank=True, default='', max_length=64)),
                ('cursor_signature', models.CharField(blank=True, default='', max_length=128)),
                ('last_sync_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_cursors', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'sync_device_cursor',
                'unique_together': {('tenant', 'device_id', 'entity_type')},
            },
        ),
        migrations.CreateModel(
            name='SyncedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('entity_type', models.CharField(db_index=True, max_length=64)),
                ('entity_id', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('hlc_wall_ms', models.BigIntegerField(default=0)),
                ('hlc_logical', models.BigIntegerField(default=0)),
                ('hlc_node_id', models.CharField(default='server', max_length=64)),
                ('is_deleted', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synced_records', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'sync_replica',
                'indexes': [models.Index(fields=['tenant', 'entity_type', 'hlc_wall_ms', 'hlc_logical'], name='sync_replic_tenant__6d320d_idx')],
                'unique_together': {('tenant', 'entity_type', 'entity_id')},
            },
        ),
        migrations.CreateModel(
            name='SyncInbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('device_id', models.CharField(db_index=True, max_length=128)),
                ('client_op_id', models.CharField(db_index=True, max_length=64)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.CharField(blank=True, default='', max_length=64)),
                ('operation', models.CharField(max_length=16)),
                ('result_status', models.CharField(choices=[('APPLIED', 'Applied'), ('CONFLICT', 'Conflict'), ('REJECTED', 'Rejected')], max_length=16)),
                ('result_payload', models.JSONField(default=dict)),
                ('conflict_code', models.CharField(blank=True, default='', max_length=16)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_inbox', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'sync_inbox',
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='sync_inbox_tenant__da4a84_idx')],
                'unique_together': {('tenant', 'device_id', 'client_op_id')},
            },
        ),
        migrations.CreateModel(
            name='SyncOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('entity_type', models.CharField(max_length=64)),
                ('entity_id', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_outbox', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'sync_outbox',
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='sync_outbox_tenant__7b6fa3_idx')],
            },
        ),
    ]
