# Generated by Django 5.1.15 on 2026-07-09 21:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.itemcategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_categories', to='tenancy.tenant')),
            ],
            options={
                'verbose_name_plural': 'item categories',
                'db_table': 'inventory_item_category',
                'unique_together': {('tenant', 'code')},
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('is_base', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uoms', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'inventory_uom',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('sku', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('tracking_type', models.CharField(choices=[('NONE', 'None'), ('BATCH', 'Batch'), ('SERIAL', 'Serial')], default='NONE', max_length=16)),
                ('negative_stock_policy', models.CharField(choices=[('STRICT', 'Strict'), ('WARN', 'Warn'), ('SILENT', 'Silent')], default='STRICT', max_length=16)),
                ('standard_rate', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tenancy.tenant')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.itemcategory')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.unitofmeasure')),
            ],
            options={
                'db_table': 'inventory_item',
            },
        ),
        migrations.CreateModel(
            name='ItemWarehouseBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('on_hand_qty', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=28)),
                ('reserved_qty', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=28)),
                ('valuation_rate', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=28)),
                ('stock_value', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=28)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_balances', to='inventory.item')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_balances', to='tenancy.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_balances', to='tenancy.warehouse')),
            ],
            options={
                'db_table': 'inventory_item_warehouse_balance',
                'indexes': [models.Index(fields=['tenant', 'warehouse'], name='inventory_i_tenant__07b3fb_idx')],
                'unique_together': {('item', 'warehouse')},
            },
        ),
        migrations.CreateModel(
            name='StockLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('posting_datetime', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('posting_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('voucher_type', models.CharField(choices=[('OPENING', 'Opening'), ('ADJUSTMENT', 'Adjustment'), ('GRN', 'GRN'), ('DELIVERY', 'Delivery'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In'), ('POS_SALE', 'POS Sale'), ('RETURN_IN', 'Return In'), ('RETURN_OUT', 'Return Out')], db_index=True, max_length=32)),
                ('voucher_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('voucher_line_id', models.UUIDField(default=uuid.uuid4)),
                ('idempotency_key', models.CharField(db_index=True, max_length=128)),
                ('qty', models.DecimalField(decimal_places=8, max_digits=28)),
                ('direction', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=8)),
                ('valuation_rate', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=28)),
                ('stock_value_change', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=28)),
                ('balance_qty', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=28)),
                ('balance_value', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=28)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('posted_by', models.UUIDField(blank=True, null=True)),
                ('is_reversed', models.BooleanField(default=False)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger_entries', to='tenancy.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger_entries', to='tenancy.company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger_entries', to='inventory.item')),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='inventory.stockledgerentry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger_entries', to='tenancy.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger_entries', to='tenancy.warehouse')),
            ],
            options={
                'db_table': 'inventory_stock_ledger_entry',
                'ordering': ['posting_datetime', 'created_at'],
                'indexes': [models.Index(fields=['tenant', 'item', 'warehouse', 'posting_date'], name='inventory_s_tenant__f0410f_idx'), models.Index(fields=['tenant', 'voucher_type', 'voucher_id'], name='inventory_s_tenant__5a304b_idx')],
                'unique_together': {('tenant', 'idempotency_key')},
            },
        ),
        migrations.AddIndex(
            model_name='unitofmeasure',
            index=models.Index(fields=['tenant', 'code'], name='inventory_u_tenant__360376_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unitofmeasure',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'is_active'], name='inventory_i_tenant__09634c_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['tenant', 'name'], name='inventory_i_tenant__f2ca84_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('tenant', 'sku')},
        ),
    ]
