# Generated by Django 5.1.15 on 2026-07-09 23:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('INVENTORY', 'Inventory'), ('SALES', 'Sales'), ('PURCHASE', 'Purchase'), ('FINANCE', 'Finance'), ('CRM', 'CRM'), ('HRM', 'HRM'), ('DASHBOARD', 'Dashboard')], db_index=True, max_length=16)),
                ('description', models.TextField(blank=True, default='')),
                ('permission_code', models.CharField(default='reports.run', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('supports_async', models.BooleanField(default=False)),
                ('default_format', models.CharField(default='JSON', max_length=16)),
            ],
            options={
                'db_table': 'reports_definition',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ReportRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=16)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.UUIDField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='reports.reportdefinition')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_runs', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'reports_run',
                'indexes': [models.Index(fields=['tenant', 'status', 'created_at'], name='reports_run_tenant__f3422a_idx')],
            },
        ),
    ]
