# Generated by Django 5.1.15 on 2026-07-09 20:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('license_id', models.CharField(db_index=True, max_length=64)),
                ('plan', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('INVALID', 'Invalid'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=16)),
                ('license_key_fingerprint', models.CharField(max_length=128, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('modules', models.JSONField(blank=True, default=list)),
                ('max_devices', models.PositiveIntegerField(default=1)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('device_fingerprint', models.CharField(blank=True, default='', max_length=128)),
                ('activated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'licensing_tenant_license',
            },
        ),
        migrations.CreateModel(
            name='LicenseDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('device_fingerprint', models.CharField(db_index=True, max_length=128)),
                ('device_name', models.CharField(blank=True, default='', max_length=128)),
                ('platform', models.CharField(blank=True, default='web', max_length=64)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_devices', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'licensing_device',
                'unique_together': {('tenant', 'device_fingerprint')},
            },
        ),
    ]
