# Generated by Django 5.1.15 on 2026-07-09 21:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('po_number', models.CharField(db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=24)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='AED', max_length=8)),
                ('total_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='tenancy.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='tenancy.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='tenancy.warehouse')),
            ],
            options={
                'db_table': 'purchase_order',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('qty_ordered', models.DecimalField(decimal_places=8, max_digits=28)),
                ('qty_received', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=28)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='po_lines', to='inventory.item')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchase.purchaseorder')),
            ],
            options={
                'db_table': 'purchase_order_line',
                'ordering': ['line_no'],
                'unique_together': {('purchase_order', 'line_no')},
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('code', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('address', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'purchase_supplier',
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='purchase.supplier'),
        ),
        migrations.CreateModel(
            name='GoodsReceiptNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('grn_number', models.CharField(db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=16)),
                ('receipt_date', models.DateField(default=django.utils.timezone.now)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('post_idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('posted_by', models.UUIDField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grns', to='tenancy.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='tenancy.warehouse')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='purchase.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='purchase.supplier')),
            ],
            options={
                'db_table': 'purchase_grn',
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('qty_received', models.DecimalField(decimal_places=8, max_digits=28)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grn_lines', to='inventory.item')),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchase.goodsreceiptnote')),
                ('purchase_order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grn_lines', to='purchase.purchaseorderline')),
            ],
            options={
                'db_table': 'purchase_grn_line',
                'ordering': ['line_no'],
                'unique_together': {('grn', 'line_no')},
            },
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['tenant', 'is_active'], name='purchase_su_tenant__a0db5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['tenant', 'status', 'order_date'], name='purchase_or_tenant__7f62b5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorder',
            unique_together={('tenant', 'po_number')},
        ),
        migrations.AddIndex(
            model_name='goodsreceiptnote',
            index=models.Index(fields=['tenant', 'status', 'receipt_date'], name='purchase_gr_tenant__b65325_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='goodsreceiptnote',
            unique_together={('tenant', 'grn_number')},
        ),
    ]
