# Generated by Django 5.1.15 on 2026-07-09 21:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('code', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('address', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'sales_customer',
            },
        ),
        migrations.CreateModel(
            name='PosSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('draft_number', models.CharField(db_index=True, max_length=32)),
                ('invoice_number', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('VOID', 'Void')], db_index=True, default='DRAFT', max_length=16)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('MIXED', 'Mixed')], default='CASH', max_length=16)),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('post_idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('device_fingerprint', models.CharField(blank=True, default='', max_length=128)),
                ('posted_by', models.UUIDField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sales', to='sales.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_sales', to='tenancy.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sales', to='tenancy.warehouse')),
            ],
            options={
                'db_table': 'pos_sale',
            },
        ),
        migrations.CreateModel(
            name='PosSaleLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('qty', models.DecimalField(decimal_places=8, max_digits=28)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sale_lines', to='inventory.item')),
                ('pos_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.possale')),
            ],
            options={
                'db_table': 'pos_sale_line',
                'ordering': ['line_no'],
            },
        ),
        migrations.CreateModel(
            name='PosTerminal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('code', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_terminals', to='tenancy.branch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_terminals', to='tenancy.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_terminals', to='tenancy.warehouse')),
            ],
            options={
                'db_table': 'pos_terminal',
            },
        ),
        migrations.AddField(
            model_name='possale',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.posterminal'),
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('so_number', models.CharField(db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('PARTIALLY_DELIVERED', 'Partially Delivered'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=24)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('currency', models.CharField(default='AED', max_length=8)),
                ('total_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='tenancy.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='sales.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='tenancy.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='tenancy.warehouse')),
            ],
            options={
                'db_table': 'sales_order',
            },
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('delivery_number', models.CharField(db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=16)),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('post_idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('posted_by', models.UUIDField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='sales.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_notes', to='tenancy.tenant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='tenancy.warehouse')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='sales.salesorder')),
            ],
            options={
                'db_table': 'sales_delivery_note',
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('qty_ordered', models.DecimalField(decimal_places=8, max_digits=28)),
                ('qty_delivered', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=28)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='so_lines', to='inventory.item')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesorder')),
            ],
            options={
                'db_table': 'sales_order_line',
                'ordering': ['line_no'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('qty_delivered', models.DecimalField(decimal_places=8, max_digits=28)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=18)),
                ('amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_lines', to='inventory.item')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.deliverynote')),
                ('sales_order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_lines', to='sales.salesorderline')),
            ],
            options={
                'db_table': 'sales_delivery_line',
                'ordering': ['line_no'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tenant', 'is_active'], name='sales_custo_tenant__71f8a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('tenant', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='possaleline',
            unique_together={('pos_sale', 'line_no')},
        ),
        migrations.AddIndex(
            model_name='posterminal',
            index=models.Index(fields=['tenant', 'is_active'], name='pos_termina_tenant__945df2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='posterminal',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='possale',
            index=models.Index(fields=['tenant', 'status', 'sale_date'], name='pos_sale_tenant__b02e07_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='possale',
            unique_together={('tenant', 'draft_number')},
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['tenant', 'status', 'order_date'], name='sales_order_tenant__e3cc3f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesorder',
            unique_together={('tenant', 'so_number')},
        ),
        migrations.AddIndex(
            model_name='deliverynote',
            index=models.Index(fields=['tenant', 'status', 'delivery_date'], name='sales_deliv_tenant__d4f958_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deliverynote',
            unique_together={('tenant', 'delivery_number')},
        ),
        migrations.AlterUniqueTogether(
            name='salesorderline',
            unique_together={('sales_order', 'line_no')},
        ),
        migrations.AlterUniqueTogether(
            name='deliveryline',
            unique_together={('delivery', 'line_no')},
        ),
    ]
