# Generated by Django 5.1.15 on 2026-07-09 22:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('code', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='tenancy.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='hrm.department')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'hrm_department',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('employee_code', models.CharField(db_index=True, max_length=32)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(blank=True, default='', max_length=128)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('designation', models.CharField(blank=True, default='', max_length=128)),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('TERMINATED', 'Terminated')], db_index=True, default='ACTIVE', max_length=16)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='tenancy.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='tenancy.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='hrm.department')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'hrm_employee',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('attendance_date', models.DateField(db_index=True)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LEAVE', 'On Leave'), ('HALF_DAY', 'Half Day')], db_index=True, default='PRESENT', max_length=16)),
                ('remarks', models.CharField(blank=True, default='', max_length=255)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='tenancy.tenant')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hrm.employee')),
            ],
            options={
                'db_table': 'hrm_attendance_record',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('leave_type', models.CharField(choices=[('ANNUAL', 'Annual'), ('SICK', 'Sick'), ('UNPAID', 'Unpaid')], default='ANNUAL', max_length=16)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('days', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=16)),
                ('approved_by', models.UUIDField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hrm.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'hrm_leave_request',
            },
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['tenant', 'company', 'is_active'], name='hrm_departm_tenant__1ec441_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('tenant', 'company', 'code')},
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['tenant', 'status', 'join_date'], name='hrm_employe_tenant__18fb27_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('tenant', 'employee_code')},
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['tenant', 'attendance_date', 'status'], name='hrm_attenda_tenant__1424ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('tenant', 'employee', 'attendance_date')},
        ),
        migrations.AddIndex(
            model_name='leaverequest',
            index=models.Index(fields=['tenant', 'status', 'from_date'], name='hrm_leave_r_tenant__e281d4_idx'),
        ),
    ]
