# Generated by Django 5.1.15 on 2026-07-09 22:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('code', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=16)),
                ('subtype', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('AR', 'Accounts Receivable'), ('AP', 'Accounts Payable'), ('INVENTORY', 'Inventory'), ('COGS', 'Cost of Goods Sold'), ('REVENUE', 'Revenue'), ('TAX_PAYABLE', 'Tax Payable'), ('GRIR', 'GR/IR Clearing'), ('OTHER', 'Other')], default='OTHER', max_length=16)),
                ('is_group', models.BooleanField(default=False)),
                ('is_reconcilable', models.BooleanField(default=False)),
                ('currency', models.CharField(default='AED', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='tenancy.company')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounting.account')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'accounting_account',
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('name', models.CharField(max_length=32)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_years', to='tenancy.company')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_years', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'accounting_fiscal_year',
            },
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('name', models.CharField(max_length=32)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('SOFT_CLOSE', 'Soft Close'), ('CLOSED', 'Closed'), ('LOCKED', 'Locked')], db_index=True, default='OPEN', max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_periods', to='tenancy.company')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_periods', to='tenancy.tenant')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='accounting.fiscalyear')),
            ],
            options={
                'db_table': 'accounting_fiscal_period',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('voucher_no', models.CharField(db_index=True, max_length=32)),
                ('posting_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('source_doc_type', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('source_doc_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('currency', models.CharField(default='AED', max_length=8)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('REVERSED', 'Reversed')], db_index=True, default='DRAFT', max_length=16)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('posted_by', models.UUIDField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='tenancy.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='tenancy.company')),
                ('fiscal_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.fiscalperiod')),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='accounting.journalentry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'accounting_journal_entry',
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('debit', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=28)),
                ('credit', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=28)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('party_type', models.CharField(blank=True, default='', max_length=32)),
                ('party_id', models.UUIDField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
            ],
            options={
                'db_table': 'accounting_journal_line',
                'ordering': ['line_no'],
            },
        ),
        migrations.CreateModel(
            name='GeneralLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('posting_date', models.DateField(db_index=True)),
                ('debit', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=28)),
                ('credit', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=28)),
                ('currency', models.CharField(default='AED', max_length=8)),
                ('correlation_id', models.UUIDField(db_index=True)),
                ('source_doc_type', models.CharField(blank=True, default='', max_length=32)),
                ('source_doc_id', models.UUIDField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gl_entries', to='accounting.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gl_entries', to='tenancy.company')),
                ('fiscal_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gl_entries', to='accounting.fiscalperiod')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gl_entries', to='tenancy.tenant')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gl_entries', to='accounting.journalentry')),
                ('journal_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gl_entries', to='accounting.journalline')),
            ],
            options={
                'db_table': 'accounting_general_ledger_entry',
                'ordering': ['posting_date', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['tenant', 'company', 'account_type'], name='accounting__tenant__940d73_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('tenant', 'company', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='fiscalyear',
            unique_together={('tenant', 'company', 'name')},
        ),
        migrations.AddIndex(
            model_name='fiscalperiod',
            index=models.Index(fields=['tenant', 'company', 'status'], name='accounting__tenant__68cb2c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fiscalperiod',
            unique_together={('tenant', 'company', 'name')},
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['tenant', 'status', 'posting_date'], name='accounting__tenant__39a482_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together={('tenant', 'voucher_no')},
        ),
        migrations.AlterUniqueTogether(
            name='journalline',
            unique_together={('journal_entry', 'line_no')},
        ),
        migrations.AddIndex(
            model_name='generalledgerentry',
            index=models.Index(fields=['tenant', 'company', 'posting_date'], name='accounting__tenant__1195d7_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledgerentry',
            index=models.Index(fields=['tenant', 'account', 'posting_date'], name='accounting__tenant__fec545_idx'),
        ),
    ]
