# Generated by Django 5.1.15 on 2026-07-09 22:30

import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('activity_type', models.CharField(choices=[('CALL', 'Call'), ('MEETING', 'Meeting'), ('EMAIL', 'Email'), ('NOTE', 'Note'), ('TASK', 'Task')], default='NOTE', max_length=16)),
                ('subject', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=16)),
            ],
            options={
                'db_table': 'crm_activity',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('lead_number', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('LOST', 'Lost'), ('CONVERTED', 'Converted')], db_index=True, default='NEW', max_length=16)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'crm_lead',
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_version', models.BigIntegerField(default=1)),
                ('opp_number', models.CharField(db_index=True, max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('stage', models.CharField(choices=[('PROSPECTING', 'Prospecting'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost')], db_index=True, default='PROSPECTING', max_length=16)),
                ('expected_value', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('probability', models.PositiveSmallIntegerField(default=10)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('remarks', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'crm_opportunity',
            },
        ),
    ]
