# Generated by Django 5.1.15 on 2026-07-09 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('hrm', '0001_initial'),
        ('sales', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_activities', to='hrm.employee'),
        ),
        migrations.AddField(
            model_name='activity',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_activities', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='lead',
            name='converted_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_leads', to='sales.customer'),
        ),
        migrations.AddField(
            model_name='lead',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_leads', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='activity',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='sales.customer'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_opportunities', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='activity',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.opportunity'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='crm_lead_tenant__bded73_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lead',
            unique_together={('tenant', 'lead_number')},
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['tenant', 'stage', 'expected_close_date'], name='crm_opportu_tenant__3e6974_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='opportunity',
            unique_together={('tenant', 'opp_number')},
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['tenant', 'status', 'due_at'], name='crm_activit_tenant__91a53e_idx'),
        ),
    ]
